### ISSUE TITLE
How to import into GM2? LFX's License?

### ISSUE THREAD

**Issue by bilouw** [EmperorCookie/LFX#1]
Hi!

Your Lfx shader seems to be a nice lighting system. I tried to import the project, it work (with strange behaviour on view size and shader compile errors). But when a i try to import the extension in an empty project, init lfx and add one light (with a sprite draw with lfx_draw_self()), the screen stay black ... Do you know if your project can be importing in GMS 2 properly? Also, can we use your system for professional content?

Thanks.

**Comment by EmperorCookie** [comment]
Hi, you need a white background because it is a subtractive lighting
engine. If your material (background) is black, no amount of light is going
to make it appear, just like in real life.

Thank you,
Fred

**Comment by bilouw** [comment]
Thanks for your answer! I change the background and it work better ^^! I don't understand everything yet but now that i have at least one light i will search more for my self :)! But still, you didn't tell me, can we use your lighting system for commercial game? I searched desperately a 2d lighting system like yours with normal map and some cool features, but i can't find one who works on GM2, free, and powerful. Why did you stop the dev of this lighting system?

PS : Many errors in shaders compilation are output when running the project, maybe that could affect the way the light and other object works.

**Comment by EmperorCookie** [comment]
This might eventually be released on the GameMaker Marketplace for free so it is using their license terms. In simple terms, yes it's okay to use for commercial games.

The reason it doesn't work in GMS 2 is because it was made for 1.4. There shouldn't be many changes needed for GMS 2.

As for the compile errors, I'm not sure why, could you open a separate issue for those, including details like GMS version and a stack trace?
